openapi: 3.0.0
info:
  title: Images API
  version: 1.0.0
  description: API for managing and serving images

servers:
  - url: http://192.168.86.242:8081
    description: Local development server

paths:
  /images:
    get:
      summary: List images
      description: Returns a paginated list of images
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
          description: Page number for pagination
        - name: pageSize
          in: query
          schema:
            type: integer
            default: 10
          description: Number of items per page
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Image'
                  total:
                    type: integer
                  page:
                    type: integer
                  totalPages:
                    type: integer
                  pageSize:
                    type: integer

  /images/{id}:
    get:
      summary: Get image by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Image ID
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Image'
        '404':
          description: Image not found

  /images/search:
    get:
      summary: Search images
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
          description: Search query
        - name: page
          in: query
          schema:
            type: integer
            default: 1
          description: Page number
        - name: pageSize
          in: query
          schema:
            type: integer
            default: 10
          description: Items per page
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Image'
                  total:
                    type: integer
                  page:
                    type: integer
                  totalPages:
                    type: integer
                  pageSize:
                    type: integer

  /health:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: Service is healthy
        '500':
          description: Service is unhealthy

components:
  schemas:
    Image:
      type: object
      properties:
        id:
          type: string
        path:
          type: string
        size:
          type: integer
        modifiedDate:
          type: string
          format: date-time
        baseAttributes:
          type: object
          properties:
            width:
              type: integer
            height:
              type: integer
            format:
              type: string
            tags:
              type: array
              items:
                type: string
